name: Label PR with team:viewer when first opened
on:
  pull_request:
    types:
      - opened
jobs:
  label_pr:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - run: gh pr edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          LABELS: "team:viewer"
